# Example KiPlot config file
kibot:
  version: 1

global:
  output: '%f_v%r_%V_%i.%x' # {projectname}_v{version}_{outputtype}_{file_id}.{extension}

variants:
  - name: 'SR'
    comment: 'GP20 Shredder'
    type: kibom
    variant: SR

  - name: 'GR'
    comment: 'GP20 Granulator'
    type: kibom
    variant: GR

preflight:
  set_text_variables:
    - variable: 'date'
      command: 'git log -1 --format="%as" -- $KIBOT_SCH_NAME' #Last modification date of schematic file
    - variable: 'version'
      text: '1.2.4' #get from tag
  run_erc: false
  run_drc: false
  check_zone_fills: true
  ignore_unconnected: false
  update_xml: true

outputs:
  - name: 'ibom'
    comment: 'Interactive Bill of Materials'
    type: ibom
    dir: Bill of materials
    options:
      dark_mode: true
      extra_fields: 'Partnumber'

  - name: 'bom'
    comment: 'Bill of Materials'
    type: bom
    dir: Bill of materials
    options: 
      format: XLSX
      columns:
        - Quantity Per PCB
        - References
        - Value
        - Footprint
        - Manufacturer
        - Partnumber
      xlsx:
        col_colors: false
        logo: false
        title: 'Bill of materials'
        max_col_width: 999
      count_smd_tht: true
      ref_separator: ','
      exclude_filter: ''

  - name: 'print_sch'
    comment: "Print schematic (PDF)"
    type: pdf_sch_print
    dir: Schematic
    #options:
      #output: Schematic.pdf

      #dnf_filter: 'dnp'
