# Example KiPlot config file
kibot:
  version: 1

global:
  output: '%f_v%r_%i.%x' #projectname_version_outputtype_file_id.extension

variants:
  - name: 'SR'
    comment: 'GP20 Shredder'
    type: kibom
    file_id: '_SR'
    variant: SR

  - name: 'GR'
    comment: 'GP20 Granulator'
    type: kibom
    file_id: '_GR'
    variant: GR

preflight:
  set_text_variables:
    - variable: 'version'
      text: '1.2.4'
    - variable: 'date'
      text: 'today'

  run_erc: false
  update_xml: true
  run_drc: false
  check_zone_fills: true
  ignore_unconnected: false
  

outputs:
  - name: 'ibom'
    comment: 'Interactive Bill of Materials'
    type: ibom
    dir: Bill of materials
    options:
      dark_mode: true
      extra_fields: 'Partnumber'


  - name: 'bom'
    comment: 'Bill of Materials'
    type: bom
    dir: Bill of materials
    options: 
      format: XLSX
      columns:
        - Quantity Per PCB
        - References
        - Value
        - Footprint
        - Manufacturer
        - Partnumber
      xlsx:
        col_colors: false
        logo: false
        title: 'Bill of materials'
      count_smd_tht: true
      ref_seperator: ','

      #dnf_filter: 'dnp'
