# Example KiPlot config file
kibot:
  version: 1

global:
  output: '%f_%r_%i%g.%x' #projectname_version_outputtype_file_id.extension

variants:
  - name: 'SR'
    comment: 'GP20 Shredder'
    type: kibom
    file_id: '_SR'
    variant: SR

  - name: 'GR'
    comment: 'GP20 Granulator'
    type: kibom
    file_id: '_GR'
    variant: GR

preflight:
  run_erc: false
  update_xml: true
  run_drc: false
  check_zone_fills: true
  ignore_unconnected: false
  set_text_variables:
    - name: 'version'
      command: 'echo 1.2.3'

outputs:
  
  - name: 'bom'
    comment: 'Bill of Materials'
    type: bom
    dir: Bill of materials
    options: 
      format: XLSX
      columns:
        - Quantity Per PCB
        - References
        - Value
        - Footprint
        - Manufacturer
        - Partnumber
      xlsx:
        col_colors: false
        logo: false
        generate_dnf: true
        title: Bill of materials
      count_smd_tht: true

  - name: 'position'
    comment: "Pick and place file, XYRS style"
    type: bom
    options:
      output: '%f.XYRS'
      units: mils
      group_fields: []
      sort_style: ref
      use_aux_axis_as_origin: true
      ignore_dnf: false
      footprint_populate_values: '0,1'
      footprint_type_values: '1,2,0'
      csv:
        separator: '	'
        hide_pcb_info: true
        hide_stats_info: true
        hide_header: false
      columns:
        - field: References
          name: Designator
        - field: Footprint X
          name: X-Loc
        - field: Footprint Y
          name: Y-Loc
        - field: Footprint Rot
          name: Rotation
        - field: Footprint Side
          name: Side
        - field: Footprint Type
          name: Type
        - field: Footprint X-Size
          name: X-Size
        - field: Footprint Y-Size
          name: Y-Size
        - field: Value
        - field: Footprint
        - field: Footprint Populate
          name: Populate
        - field: MPN
