name: Generate-3D-Prints

on:
  push:
    paths:
      - 'pnp/cad/**.FCStd'
      - '.github/workflows/generate-3d-prints.yaml'
    ignore-tags:
      - '*'
  pull_request:
    paths:
      - 'pnp/cad/**.FCStd'
    ignore-tags:
      - '*'
  workflow_dispatch:

jobs:
  generate-obj:
    name: Generate STL file artifacts
    runs-on: ubuntu-latest

    steps:
    - name: Download repository
      uses: actions/checkout@v2

    - name: Install FreeCAD Python library
      run:  |
        sudo apt install python3
        python3 -m pip install --upgrade pip
        pip install PySide2

    - name: Fetch FreeCAD
      uses: dsaltares/fetch-gh-release-asset@master
      with:
        repo: "FreeCAD/FreeCAD"
        version: "tags/0.19.2"
        file: "FreeCAD_0.19-24291-Linux-Conda_glibc2.12-x86_64.AppImage"
        target: "FreeCAD.AppImage"
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Install FreeCad
      run:  |
        sudo chown runner:docker FreeCAD.AppImage
        chmod +x FreeCAD.AppImage
        ./FreeCAD.AppImage --appimage-extract > /dev/null

    - name: Generate DXF files
      run: |        
        cd pnp/cad
        python3 export-csm.py

    - name: Generate STL files
      run: |
        cd pnp/cad
        rm 3D-Prints/*
        python3 export-3d-files.py

    - name: Compress STL files
      run: |
        cd pnp/cad/3D-Prints
        zip -9 -j ~/3d-prints_${{ github.ref_name }}_${{ github.sha }}.zip *.stl
        cd pnp/cad/CSM-Output
        zip -9 -j -u ~/3d-prints_${{ github.ref_name }}_${{ github.sha }}.zip *.dxf

    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: 3d-prints
        path: ~/3d-prints_${{ github.ref_name }}_${{ github.sha }}.zip
        if-no-files-found: error
