name: generate-3d-print-information

on:
  push:
    branches:
      - assembly-guide
    paths:
      - 'pnp/cad/slice-3d-files.py'
      - 'pnp/cad/PrusaSlicerConfig.ini'
      - '!pnp/cad/3D-Prints/**'
      - '.github/workflows/generate-3d-print-information.yaml'
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  generate-obj:
    name: Generate G-Code files and info for documentation
    runs-on: ubuntu-20.04

    steps:
    - name: Update system repositories
      run:  sudo apt update

    - name: Install missing modules
      run:  sudo apt install libcanberra-gtk-module libcanberra-gtk3-module libglu1-mesa libgl1 libpangox-1.0-0 libpangoxft-1.0-0

    - name: Download repository
      uses: actions/checkout@v2

    - name: Download PrusaSlicer
      run: |
           wget --content-disposition --quiet https://github.com/prusa3d/PrusaSlicer/releases/download/version_2.3.1/PrusaSlicer-2.3.1+linux-x64-202104161339.AppImage
           mv PrusaSlicer-* PrusaSlicer.AppImage

    - name: Install PrusaSlicer 2
      run: export SSL_CERT_FILE=/etc/ssl/certs/ca-certificates.crt

    - name: Install PrusaSlicer 3
      run: chmod a+x PrusaSlicer.AppImage 

    - name: Remove existing 3D Print Reference Directory
      run: |
           rm -dfr doc/content/en/docs/reference/3dprint
           mkdir -p doc/content/en/docs/reference/3dprint

    - name: Generate 3D files
      run: |
        cd pnp/cad
        python slice-3d-files.py

    - name: Commit files
      run: |

        git add -f doc/content/en/docs/reference/3dprint
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git commit -m "CI: Generate 3D print information" -a | exit 0

    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: ${{ github.ref }}
