name: Index-3D-Prints

on: push

jobs:
  generate-obj:
    name: Generate OBJ files
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Install FreeCAD
      run: sudo apt install freecad

    - name: setup python
      uses: actions/setup-python@v2
      with:
       python-version: 3.9

   - name: execute py script
     run: |
       cd pnp/cad
       rm -rf 3D-Prints
       mkdir 3D-Prints
       python3 export-3d-files.py