name: generate-mobo-pcb-artifacts

on:
  release:
    types: [ published ]  
  workflow_dispatch:
    #Add options?
    
jobs:
  generate-artifacts:
    runs-on: ubuntu-latest
    container: setsoft/kicad_auto:dev_k6
      
    steps:
    - name: Update system repositories and install required libraries
      run: |
        apt update
        apt -y install git zip

    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Run KiBot
      run: |
        cd PCB/mobo
        rm -rf ../../export
        kibot -c ../../config-4layer.kibot.yaml -e mobo.kicad_sch -b mobo.kicad_pcb -d ../../export

        
    - name: Prepare Output Artifact
      run: |
        cd export
        zip -r pnp_mobo_files.zip *

    - name: Upload Artifacts to Workflow Run
      uses: actions/upload-artifact@v2
      with:
        name: pnp_mobo_files
        path: export/pnp_mobo_files.zip

    - name: Upload Artifacts to Release
      uses: softprops/action-gh-release@v1
      if: github.event_name == 'release'
      with:
        files: |
          export/pnp_mobo_files.zip
