name: generate-mobo-pcb-artifacts

on:
  release:
    types: [ published ]  
  workflow_dispatch:
    
#env:
# key: value

jobs:
  generate-artifacts:
    runs-on: ubuntu-latest
    container: setsoft/kicad_auto:dev_k6
      
    steps:
    - name: Update system repositories and install required libraries
      run: |
        apt update
        apt -y install git zip
        apt install python3-pip
        pip3 install -e .

    - name: Checkout Repository
      uses: actions/checkout@v2     

    - name: Update the PCBs with string
      run: |
        sed -i "s!<<hash>>!"testje"!" pnp/pcb/mobo/mobo.kicad_pcb

    - name: Run KiBot
      run: |
        cd pnp/pcb/mobo
        rm -rf export/
        kibot -c ../../../config-4layer.kibot.yaml -e mobo.kicad_sch -b mobo.kicad_pcb -d export

    # Splitting this out to ensure a failed kibot run will mark a check as failed.
    - name: Prepare gerber
      run: |
        cd pnp/pcb/mobo/export/Gerbers
        zip -r -j pnp_mobo_gerbers.zip *
        
    - name: Prepare Output Artifact
      run: |
        cd pnp/pcb/mobo/export/
        zip -r -j ../pnp_mobo_files.zip *

    - name: Upload Artifacts to Workflow Run
      uses: actions/upload-artifact@v2
      with:
        name: pnp_mobo_output
        path: pnp/pcb/mobo/export

    - name: Upload Artifacts to Release
      uses: softprops/action-gh-release@v1
      if: github.event_name == 'release'
      with:
        files: |
          pnp/pcb/mobo/pnp_mobo_files.zip
