name: Index-3D-Prints

on: push

jobs:
  generate-obj:
    name: Generate OBJ files
    runs-on: ubuntu-20.04

    steps:
    - name: Install FreeCAD
      run: |
        sudo apt update
        sudo apt install freecad
        sudo apt install libnglib-6.2.1804

    - name: Download repository
      uses: actions/checkout@v2

    - name: Generate 3D files
      run: |
        cd pnp/cad
        rm -rf 3D-Prints
        mkdir 3D-Prints
        python export-3d-files.py

    - name: Commit files
      run: |
        git add .
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git commit -m "CI: Generate 3D Prints" -a | exit 0

    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}